<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'upload.subscriber' shared service.

return $this->services['upload.subscriber'] = new \Upload\UploadBundle\Listener\UploadSubscriber(${($_ = isset($this->services['upload.annotation_reader']) ? $this->services['upload.annotation_reader'] : $this->load(__DIR__.'/getUpload_AnnotationReaderService.php')) && false ?: '_'}, ${($_ = isset($this->services['upload.handler']) ? $this->services['upload.handler'] : $this->services['upload.handler'] = new \Upload\UploadBundle\Handler\UploadHandler()) && false ?: '_'});
