<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7t4bjlf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7t4bjlf/appProdProjectContainer.php') {
    touch(__DIR__.'/Container7t4bjlf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container7t4bjlf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container7t4bjlf\appProdProjectContainer(array(
    'container.build_hash' => '7t4bjlf',
    'container.build_id' => '362156cd',
    'container.build_time' => 1520871432,
));
