<?php

namespace Proxies\__CG__\FP\CMSBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Patient extends \FP\CMSBundle\Entity\Patient implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'id', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'matricule', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'nomPatient', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'prenomPatient', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'genrePatient', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'telPatient', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'terrainparticulier', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'filename', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'file', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'situationFamiliale', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'adressePatient', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'numerodossier', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'email', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'groupeSanguin', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'statut', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'dateNaiss', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'dateAjout', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'type_patient', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'structure', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'tuteur'];
        }

        return ['__isInitialized__', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'id', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'matricule', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'nomPatient', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'prenomPatient', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'genrePatient', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'telPatient', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'terrainparticulier', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'filename', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'file', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'situationFamiliale', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'adressePatient', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'numerodossier', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'email', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'groupeSanguin', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'statut', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'dateNaiss', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'dateAjout', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'type_patient', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'structure', '' . "\0" . 'FP\\CMSBundle\\Entity\\Patient' . "\0" . 'tuteur'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Patient $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricule($matricule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricule', [$matricule]);

        return parent::setMatricule($matricule);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricule', []);

        return parent::getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomPatient($nomPatient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomPatient', [$nomPatient]);

        return parent::setNomPatient($nomPatient);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomPatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomPatient', []);

        return parent::getNomPatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomPatient($prenomPatient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomPatient', [$prenomPatient]);

        return parent::setPrenomPatient($prenomPatient);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomPatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomPatient', []);

        return parent::getPrenomPatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenrePatient($genrePatient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenrePatient', [$genrePatient]);

        return parent::setGenrePatient($genrePatient);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenrePatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenrePatient', []);

        return parent::getGenrePatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelPatient($telPatient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelPatient', [$telPatient]);

        return parent::setTelPatient($telPatient);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelPatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelPatient', []);

        return parent::getTelPatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituationFamiliale($situationFamiliale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituationFamiliale', [$situationFamiliale]);

        return parent::setSituationFamiliale($situationFamiliale);
    }

    /**
     * {@inheritDoc}
     */
    public function getSituationFamiliale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituationFamiliale', []);

        return parent::getSituationFamiliale();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressePatient($adressePatient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressePatient', [$adressePatient]);

        return parent::setAdressePatient($adressePatient);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressePatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressePatient', []);

        return parent::getAdressePatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumerodossier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumerodossier', []);

        return parent::getNumerodossier();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumerodossier($numerodossier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumerodossier', [$numerodossier]);

        return parent::setNumerodossier($numerodossier);
    }

    /**
     * {@inheritDoc}
     */
    public function setGroupeSanguin($groupeSanguin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroupeSanguin', [$groupeSanguin]);

        return parent::setGroupeSanguin($groupeSanguin);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupeSanguin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupeSanguin', []);

        return parent::getGroupeSanguin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaiss($dateNaiss)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaiss', [$dateNaiss]);

        return parent::setDateNaiss($dateNaiss);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaiss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaiss', []);

        return parent::getDateNaiss();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAjout($dateAjout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAjout', [$dateAjout]);

        return parent::setDateAjout($dateAjout);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAjout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAjout', []);

        return parent::getDateAjout();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypePatient(\FP\CMSBundle\Entity\TypePatient $typePatient = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypePatient', [$typePatient]);

        return parent::setTypePatient($typePatient);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypePatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypePatient', []);

        return parent::getTypePatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setTuteur(\FP\CMSBundle\Entity\Tuteur $tuteur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTuteur', [$tuteur]);

        return parent::setTuteur($tuteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getTuteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTuteur', []);

        return parent::getTuteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerrainparticulier($terrainparticulier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerrainparticulier', [$terrainparticulier]);

        return parent::setTerrainparticulier($terrainparticulier);
    }

    /**
     * {@inheritDoc}
     */
    public function getTerrainparticulier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerrainparticulier', []);

        return parent::getTerrainparticulier();
    }

    /**
     * {@inheritDoc}
     */
    public function getFilename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilename', []);

        return parent::getFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilename($filename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilename', [$filename]);

        return parent::setFilename($filename);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile($file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function setStructure(\FP\CMSBundle\Entity\Ministere $structure = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStructure', [$structure]);

        return parent::setStructure($structure);
    }

    /**
     * {@inheritDoc}
     */
    public function getStructure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructure', []);

        return parent::getStructure();
    }

}
