<?php

namespace CMSFP\TagBundle\Repository;

/**
 * PathologiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PathologiesRepository extends \Doctrine\ORM\EntityRepository
{
}
