<?php

namespace CMSFP\TagBundle\Repository;

/**
 * PathologieshRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PathologieshRepository extends \Doctrine\ORM\EntityRepository
{
}
