<?php

namespace CMSFP\TagBundle\Repository;

/**
 * TypeExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeExamenRepository extends \Doctrine\ORM\EntityRepository
{
}
