<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'upload.handler' shared service.

return $this->services['upload.handler'] = new \Upload\UploadBundle\Handler\UploadHandler();
