<?php

namespace FP\CMSBundle\Repository;

/**
 * Achat_medicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Achat_medicRepository extends \Doctrine\ORM\EntityRepository
{
}
