<?php

namespace FP\CMSBundle\Repository;

/**
 * AllergieneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllergieneRepository extends \Doctrine\ORM\EntityRepository
{
}
