<?php

namespace FP\CMSBundle\Repository;

/**
 * AllergieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllergieRepository extends \Doctrine\ORM\EntityRepository
{
}
