<?php

namespace FP\CMSBundle\Repository;

/**
 * AntecedentSFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntecedentSFRepository extends \Doctrine\ORM\EntityRepository
{
}
