<?php

namespace FP\CMSBundle\Repository;

/**
 * AntecedentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntecedentRepository extends \Doctrine\ORM\EntityRepository
{
}
