<?php

namespace FP\CMSBundle\Repository;

/**
 * Consultation_symptomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Consultation_symptomeRepository extends \Doctrine\ORM\EntityRepository
{
}
