<?php

namespace FP\CMSBundle\Repository;

/**
 * Details_ordonnanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Details_ordonnanceRepository extends \Doctrine\ORM\EntityRepository
{
}
