<?php

namespace FP\CMSBundle\Repository;

/**
 * GrossessesanterieuresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrossessesanterieuresRepository extends \Doctrine\ORM\EntityRepository
{
}
