<?php

namespace FP\CMSBundle\Repository;

/**
 * MedicamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicamentRepository extends \Doctrine\ORM\EntityRepository
{
}
