<?php

namespace FP\CMSBundle\Repository;

/**
 * MereSFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MereSFRepository extends \Doctrine\ORM\EntityRepository
{
}
