<?php

namespace FP\CMSBundle\Repository;

/**
 * MinistereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MinistereRepository extends \Doctrine\ORM\EntityRepository
{
}
