<?php

namespace FP\CMSBundle\Repository;

/**
 * OrdonnanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdonnanceRepository extends \Doctrine\ORM\EntityRepository
{
}
