<?php

namespace FP\CMSBundle\Repository;

/**
 * PathologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PathologieRepository extends \Doctrine\ORM\EntityRepository
{
}
