<?php

namespace FP\CMSBundle\Repository;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends \Doctrine\ORM\EntityRepository
{
    public function generateCode() {
//        return DB::table('orders')->where('id', DB::raw("(select max(`id`) from orders)"))->get();
        $querybuilder = $this->_em->createQueryBuilder()
            ->select('MAX(p.id)')
            ->from('FPCMSBundle:Patient', 'p')
            ->getQuery()
            ->getSingleScalarResult();
        ;
        if ($querybuilder == null) {
            return "L000001";
        }
        function randLetter()
        {
            $int = rand(0,25);
            $a_z = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            $rand_letter = $a_z[$int];
            return $rand_letter;
        }
        return 'P' . str_pad($querybuilder + 1,6,"0",STR_PAD_LEFT) . '-'. randLetter();
    }

    public function nombreTotalPatients() {
//        return DB::table('orders')->where('id', DB::raw("(select max(`id`) from orders)"))->get();
        $nbpatients = $this->_em->createQueryBuilder()
            ->select('Count(p.id)')
            ->from('FPCMSBundle:Patient', 'p')
            ->getQuery()
            ->getSingleScalarResult();
        ;
        return $nbpatients;
    }

}
