<?php

namespace FP\CMSBundle\Repository;

/**
 * PereSFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PereSFRepository extends \Doctrine\ORM\EntityRepository
{
}
