<?php

namespace FP\CMSBundle\Repository;

/**
 * SoustypeconsultationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoustypeconsultationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getsoustypeByTypeConsultation() {
        $nbconsultationsbymedecin = $this->_em->createQueryBuilder()
            ->select('s.id')
            ->from('FPCMSBundle:Soustypeconsultation', 's')
            ->leftJoin('s.typeconsultation', 't')
            ->where('t.id = :typeconsult')
            ->setParameter('typeconsult', 1)
            ->getQuery()
            ->getResult();
        return $nbconsultationsbymedecin;
    }
}
