<?php

namespace FP\CMSBundle\Repository;

/**
 * SupertypeexamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupertypeexamenRepository extends \Doctrine\ORM\EntityRepository
{
}
