<?php

namespace FP\CMSBundle\Repository;

/**
 * SymptomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SymptomeRepository extends \Doctrine\ORM\EntityRepository
{
}
