<?php

namespace FP\CMSBundle\Repository;

/**
 * TuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TuteurRepository extends \Doctrine\ORM\EntityRepository
{
}
