<?php

namespace FP\CMSBundle\Repository;

/**
 * Type_consultationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_consultationRepository extends \Doctrine\ORM\EntityRepository
{
}
