<?php

namespace FP\CMSBundle\Repository;

/**
 * Type_medicamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_medicamentRepository extends \Doctrine\ORM\EntityRepository
{
}
