<?php

namespace FP\CMSBundle\Repository;

/**
 * TypePatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePatientRepository extends \Doctrine\ORM\EntityRepository
{
}
