<?php

namespace FP\CMSBundle\Repository;

/**
 * Type_examenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_examenRepository extends \Doctrine\ORM\EntityRepository
{
}
