<?php

namespace FP\CMSBundle\Repository;

/**
 * VariablesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VariablesRepository extends \Doctrine\ORM\EntityRepository
{
}
