<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZxagsdv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZxagsdv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZxagsdv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZxagsdv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZxagsdv\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Zxagsdv',
    'container.build_id' => '752b1c25',
    'container.build_time' => 1520871426,
));
